<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\FileProcessor.Core\FileProcessor.Core.csproj">
			<Private>False</Private>
			<ExcludeAssets>runtime</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<PropertyGroup>
			<RootDir Condition="'$(SolutionDir)' != ''">$(SolutionDir)</RootDir>
			<RootDir Condition="'$(SolutionDir)' == ''">$(MSBuildProjectDirectory)\..\</RootDir>
			<PluginTarget>$(RootDir)FileProcessor.Desktop\bin\$(Configuration)\net10.0-windows\Plugins\</PluginTarget>
		</PropertyGroup>

		<Message Text="[Build Info] 插件源码路径: $(TargetDir)" Importance="high" />
		<Message Text="[Build Info] 插件分发目标: $(PluginTargetDir)" Importance="high" />

		<MakeDir Directories="$(PluginTargetDir)" />

		<Copy SourceFiles="$(TargetDir)$(TargetName).dll" DestinationFolder="$(PluginTarget)" SkipUnchangedFiles="true" />
		<Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="$(PluginTarget)" SkipUnchangedFiles="true" />

		<Message Text="[Build Success] 插件已成功同步到：$(PluginTargetDir)" Importance="high" />
	</Target>

</Project>