<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\FileProcessor\FileProcessor.csproj">
			<Private>False</Private>
			<ExcludeAssets>runtime</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<PropertyGroup>
			<ConsoleTargetDir>$(SolutionDir)ConsoleTest\bin\$(Configuration)\net10.0\Plugins\</ConsoleTargetDir>
		</PropertyGroup>

		<MakeDir Directories="$(ConsoleTargetDir)" />

		<Copy SourceFiles="$(OutputPath)$(AssemblyName).dll"
			  DestinationFolder="$(ConsoleTargetDir)"
			  SkipUnchangedFiles="true" />

		<Message Text="[Build Success] 插件已自动同步至: $(ConsoleTargetDir)" Importance="high" />
	</Target>

</Project>