<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
	</ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\FileProcessor.Core\FileProcessor.Core.csproj" />
    <ProjectReference Include="..\FileProcessor.Engine\FileProcessor.Engine.csproj" />
    <ProjectReference Include="..\FileProcessor.Infrastructure\FileProcessor.Infrastructure.csproj" />
    <ProjectReference Include="..\FileProcessor.Mediator\FileProcessor.Mediator.csproj" />
    <ProjectReference Include="..\WDisp.Plugin\WDisp.Plugin.csproj" />
    <ProjectReference Include="..\WMass.Plugin\WMass.Plugin.csproj" />
  </ItemGroup>

</Project>
