<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileProcessor.Core\FileProcessor.Core.csproj" />
    <ProjectReference Include="..\FileProcessor.Engine\FileProcessor.Engine.csproj" />
    <ProjectReference Include="..\FileProcessor.Infrastructure\FileProcessor.Infrastructure.csproj" />
    <ProjectReference Include="..\FileProcessor.Mediator\FileProcessor.Mediator.csproj" />
    <ProjectReference Include="..\WDisp.Plugin\WDisp.Plugin.csproj" />
    <ProjectReference Include="..\WMass.Plugin\WMass.Plugin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>